### ISSUE TITLE
Github Profile Fetcher

### ISSUE THREAD

**Issue by chirag-wadhwa** [chirag-wadhwa/frontend-101#13]
The request is being sent by all the three methods and the result is also displayed properly, just the name of the profile being returned is null for any case.
What could be the issue?

**Comment by jshreyans** [comment]
I'll have a look at the error. It's something trivial because the name is being fetched correctly but somehow the `innerHTML` remains unchanged. Let me see.

A couple of errors:
- The Jquery/AJAX method isn't working
- There is no error handling, as in, if a user handle that doesn't exist is entered, no error message is shown

**Comment by chirag-wadhwa** [comment]
I have made the changes. Jquery/AJAX method works. Also, when a wrong github handle is entered the screen informs the user about the same.

**Comment by jshreyans** [comment]
Good job! It works perfectly now.
